Proyecto de traducción
======================

**¡Bienvenido!**

Estás en el proyecto de traducción al Español de la documentación de Symfony2. La documentación es tan importante como el código mismo, esta también debe ser amena, correcta respecto al código y además estar actualizada.

La idea principal de este proyecto es mantener al día la documentación, no sólo de Symfony2 sino de sus paquetes adjuntos como Twig (por cierto al final de la página está el enlace) y Doctrine con todas sus variantes (``ORM``, ``DBAL``, etc.).

Si deseas colaborar puedes :doc:`leer la guía </contributing/documentation/tools_translate>` que estoy escribiendo para que te vayas familiarizando con el proceso de traducción.

¡Nuevo Jobeet2!
---------------
-----------

.. toc tree::
..   : hidden :

..   jobeet-docs/index

.. Acabo de empezar la traducción del proyecto Jobeet, la puedes ver :doc:`aquí <jobeet-docs/index>`.

Por el momento quité el enlace de Jobeet, puesto que está desactualizado (existen demasiadas inconsistencias) y no quiero contaminar las memorias de traducción con segmentos que no reflejen la traducción correcta, en cuanto reanuden la escritura continuaremos...

Doctrine2
---------

.. toctree::
   :hidden:

   orm-documentation/index

El asignador objeto↔relacional :doc:`ORM de Doctrine 2 <orm-documentation/index>`.



Comentarios
-----------

Por favor, si encuentras algún error tipográfico, o sientes que algún tema esta inconcluso o es confusa la información, déjanos una nota en el sistema de comentarios al final de cada página, **todos los comentarios y críticas son bienvenidos**.

Gracias.

**Esperamos disfrutes la lectura de estás páginas y en verdad te sea útil**.
