``widget``
~~~~~~~~~~

**tipo**: ``string`` **predeterminado**: ``choice``

La forma básica en que se debe reproducir este campo. Puede ser una de las siguientes:

* ``choice``: reproduce tres entradas de selección.  El orden de los selectores se define en la opción ``pattern``.

* ``text``: reproduce tres campos de entrada tipo texto (mes, día, año).

* ``single_text``: reproduce un sólo cuadro de tipo texto. La entrada del usuario se valida en base a la opción ``format``.
