``multiple``
~~~~~~~~~~~~

**tipo**: ``Boolean`` **predeterminado**: ``false``

Si es ``true``, el usuario podrá seleccionar varias opciones (en contraposición a elegir sólo una opción). Dependiendo del valor de la opción ``expanded``, esto reproducirá una etiqueta de selección o casillas de verificación si es ``true`` y una etiqueta de selección o botones de radio si es ``false``. El valor devuelto será una matriz.