``required``
~~~~~~~~~~~~

**tipo**: ``Boolean`` **predeterminado**: ``true``

Si es ``true``, reproducirá un `atributo required de HTML5`_. La ``label`` correspondiente será reproducida con una clase ``required``.

Esto es superficial e independiente de la validación. A lo sumo, si dejas que Symfony adivine el tipo de campo, entonces el valor de esta opción, se puede adivinar a partir de tu información de validación.

.. _`atributo required de HTML5`: http://diveintohtml5.org/forms.html