Etiqueta select, casillas de verificación o botones de radio
------------------------------------------------------------

Este campo se puede reproducir como uno de varios campos HTML, dependiendo de las opciones ``expanded`` y ``multiple``:

+------------------------------------------+-----------+----------+
| tipo elemento                            | expandido | múltiple |
+==========================================+===========+==========+
| etiqueta de selección                    | false     | false    |
+------------------------------------------+-----------+----------+
| etiqueta de selección (con atributo      | false     | true     |
| ``multiple``)                            |           |          |
+------------------------------------------+-----------+----------+
| botones de radio                         | true      | false    |
+------------------------------------------+-----------+----------+
| caja de verificación (checkboxes)        | true      | true     |
+------------------------------------------+-----------+----------+