* **Configurando paquetes**:

  * :doc:`FrameworkBundle (framework) </reference/configuration/framework>`
  * :doc:`AsseticBundle (assetic) </reference/configuration/assetic>`
  * :doc:`DoctrineBundle (doctrine) </reference/configuration/doctrine>`
  * :doc:`SecurityBundle (security) </reference/configuration/security>`
  * :doc:`SwiftMailerBundle (swiftmailer) </reference/configuration/swiftmailer>`
  * :doc:`TwigBundle (twig) </reference/configuration/twig>`
  * :doc:`MonologBundle (monolog) </reference/configuration/monolog>`
  * :doc:`WebProfilerBundle (web_profiler) </reference/configuration/web_profiler>`
  * :doc:`DoctrineMongoDBBundle (doctrine_mongodb) </reference/configuration/mongodb>`

* **Formularios**

  * :doc:`Referencia de tipos de campo en formularios </reference/forms/types>`
  * :doc:`Referencia de funciones de plantilla Twig </reference/forms/twig_reference>`

* **Otras áreas**

  * :doc:`/reference/constraints`
  * :doc:`/reference/dic_tags`
  * :doc:`/reference/YAML`
  * :doc:`/reference/requirements`
  * :doc:`/reference/model`
