* **Controladores**

  * :doc:`/cookbook/controller/error_pages`
  * :doc:`/cookbook/controller/service`

* **Enrutando**

  * :doc:`/cookbook/routing/scheme`
  * :doc:`/cookbook/routing/slash_in_parameter`

* **Manejando activos JavaScript y CSS**

  * :doc:`/cookbook/assetic/asset_management`
  * :doc:`/cookbook/assetic/yuicompressor`
  * :doc:`/cookbook/assetic/jpeg_optimize`
  * :doc:`/cookbook/assetic/apply_to_option`

* **Interacción con la base de datos (Doctrine)**

  * :doc:`/cookbook/doctrine/doctrine_fixtures`
  * :doc:`/cookbook/doctrine/mongodb`
  * :doc:`/cookbook/doctrine/migrations`
  * :doc:`/cookbook/doctrine/file_uploads`
  * :doc:`/cookbook/doctrine/common_extensions`
  * :doc:`/cookbook/doctrine/event_listeners_subscribers`
  * :doc:`/cookbook/doctrine/dbal`
  * :doc:`/cookbook/doctrine/reverse_engineering`
  * :doc:`/cookbook/doctrine/multiple_entity_managers`
  * :doc:`/cookbook/doctrine/custom_dql_functions`

* **Formularios y Validación**

  * :doc:`/cookbook/form/simple_signup_form_with_mongodb`
  * :doc:`/cookbook/form/form_customization`
  * :doc:`/cookbook/form/create_custom_field_type`
  * :doc:`/cookbook/validation/custom_constraint`
  * (doctrine) :doc:`/cookbook/doctrine/file_uploads`

* **Configuración y el contenedor de servicios**

  * :doc:`/cookbook/configuration/environments`
  * :doc:`/cookbook/configuration/external_parameters`
  * :doc:`/cookbook/service_container/factories`
  * :doc:`/cookbook/service_container/parentservices`
  * :doc:`/cookbook/configuration/pdo_session_storage`

* **Paquetes**

  * :doc:`/cookbook/bundles/best_practices`
  * :doc:`/cookbook/bundles/inheritance`
  * :doc:`/cookbook/bundles/extension`

* **Correo electrónico**

  * :doc:`/cookbook/correo`
  * :doc:`/cookbook/gmail`
  * :doc:`/cookbook/correo/dev_environment`
  * :doc:`/cookbook/correo/spool`

* **Probando**

  * :doc:`/cookbook/testing/http_authentication`
  * :doc:`/cookbook/testing/insulating_clients`
  * :doc:`/cookbook/testing/profiling`

* **Seguridad**

  * :doc:`/cookbook/security/remember_me`
  * :doc:`/cookbook/security/voters`
  * :doc:`/cookbook/security/acl`
  * :doc:`/cookbook/security/acl_advanced`
  * :doc:`/cookbook/security/force_https`
  * :doc:`/cookbook/security/form_login`
  * :doc:`/cookbook/security/securing_services`
  * :doc:`/cookbook/security/entity_provider`
  * :doc:`/cookbook/security/custom_provider`
  * :doc:`/cookbook/security/custom_authentication_provider`

* **Memoria caché**

  * :doc:`/cookbook/cache/varnish`

* **Plantillas**

  * :doc:`/cookbook/templating/PHP`

* **Herramientas, registro y funcionamiento interno**

  * :doc:`/cookbook/tools/autoloader`
  * :doc:`/cookbook/tools/finder`
  * :doc:`/cookbook/console`
  * :doc:`/cookbook/debugging`
  * :doc:`/cookbook/logging/monolog`

* **Servicios Web**

  * :doc:`/cookbook/web_services/php_soap_extension`

* **Extendiendo Symfony**

  * :doc:`/cookbook/event_dispatcher/class_extension`
  * :doc:`/cookbook/event_dispatcher/method_behavior`
  * :doc:`/cookbook/request/mime_type`
  * :doc:`/cookbook/profiler/data_collector`

* **Symfony2 para usuarios de symfony1**

  * :doc:`/cookbook/symfony1`
