* **Código**:

  * :doc:`Errores </contributing/code/bugs>` | 
  * :doc:`Parches </contributing/code/patches>` | 
  * :doc:`Seguridad </contributing/code/security>` | 
  * :doc:`Pruebas </contributing/code/tests>` | 
  * :doc:`Estándares de codificación </contributing/code/standards>` | 
  * :doc:`Convenciones de codificación </contributing/code/conventions>` | 
  * :doc:`Licencia </contributing/code/license>`

* **Documentación**:

  * :doc:`Descripción </contributing/documentation/overview>` | 
  * :doc:`Formato </contributing/documentation/format>` | 
  * :doc:`Traduciendo </contributing/documentation/translations>` | 
  * :doc:`Licencia </contributing/documentation/license>`

* **Comunidad**:

  * :doc:`Reuniones IRC </contributing/community/irc>` |
  * :doc:`Otros recursos </contributing/community/other>`
